name: Deploy Personal Site
on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.1.2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
